on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
        
      - name: Build project
        run: |
          npm install
          npm run dist
          
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no

      - name: Zip Folder
        run: |
          zip -r rank-tracker.zip . -x ".git/*" ".github/*" "node_modules/*" ".editorconfig" ".gitignore" "DOCKER_ENV" "docker_tag" "Dockerfile-php-build" "gulpfile.js" "openapi.json" "output.log" "package-lock.json" "package.json" "README.md" "composer.json" "composer.lock" "scripts" "phpcs.ruleset.xml" "webpack.config.js" "vendor/php-di/phpdoc-reader/.github" "./vendor/php-di/phpdoc-reader/.github" "./resources/css/*"
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rank-tracker.zip